services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: tinyfed_mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./results:/results

  aggregator:
    build: ./app
    container_name: tinyfed_aggregator
    env_file: .env
    environment:
      - ROLE=aggregator
    depends_on:
      - mosquitto
    volumes:
      - ./results:/results

  client:
    build: ./app
    env_file: .env
    environment:
      - ROLE=client
    deploy:
      replicas: 3
    depends_on:
      - mosquitto
      - aggregator
    volumes:
      - ./results:/results
